const message = {
    USER_NOT_FOUND:"User not found.",
    PROFILE_UPDATE:"PROFILE UPDATED SUCCESSFULLY",
    USER_REMOVE:"User Removed Successfully.",
    EMPTY_FIELD:"EMPTY FIELD SHOULD NOT ACCEPTABLE.",
    ALREADY_REGISTERED:"USER ALREADY REGISTERED.",
    REGISTERED:"REGISTERED SUCCESSFULLY.",
    NOT_REGISTERED:"USER NOT REGISTERED.",
    LOGIN_FAILED:"LOGIN FAILED.",
    LOGIN_SUCCESS:"LOGIN SUCCESSFULL.",
    AUTH_FAILED:"AUTHENTICATION FAILED.",
    FORGET_PASS:"LINK SEND SUCCESSFULLY CHECK YOUR EMAIL FOR RESET PASSWORD.",
    TOKEN_EXPIRED:"TOKEN EXPIRED.",
    PASSWORD_CHANGE:"PASSWORD CHANGED SUCCESSFULLY.",
    PASSWORD_NOT_MATCH:"PASSWORD DOESNOT MATCH",
    PASS_DIFFER:"NEW PASSWORD MUST BE DIFFERENT FROM OLD PASSWORD.",
    SOMETHING_WRONG:"SOMETHING WENT WRONG DURING UPDATION."
}

export { message };