const orderMessage = {
    ORDER_NOT_FOUND:"ORDER NOT FOUND.",
    ALREADY_DELIVERED:"YOU HAVE ALREADY DELIVERED.",
    ORDER_STATUS_UPDATED:"ORDER STATUS UPDATED SUCCESSFULLY.",
    ORDER_DELETED:"ORDER DELETED SUCCESSFULLY.",
};

export { orderMessage };